name: CHILE_WORFLOW
on: 
  workflow_run: 
    workflows: [PARENT_WORKFLOW]
    types: [completed]
jobs:
    first_job:
          runs-on: ubuntu-latest
          steps:
            - name: List and read files
              run: |
                   echo "My first Github Actions Job"