name: context Workflow
on: push
jobs:
    first_job:
          runs-on: ubuntu-latest
          steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: List and read files
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"

            - name: List and read files
              env:
                STEPS_CONTEXT: ${{ toJson(steps) }}
              run: echo "$STEPS_CONTEXT"

            - name: List and read files
              env:
                RUNNER_CONTEXT: ${{ toJson(runner) }}
              run: echo "$RUNNER_CONTEXT"
            - name: List and read files
              env:
                SECRETS_CONTEXT: ${{ toJson(secrets) }}
              run: echo "$SECRETS_CONTEXT"          