name: If Workflow
on: push
jobs:
    first_job:
          if: github.ref == 'refs/heads/main'
          runs-on: ubuntu-latest
          steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: List and read files
              run: |
                   echo "My first Github Actions Job"
                   ls -ltra
                   cat README.md
                   sudo apt-get install cowsay -y
            - name: Geneerate ASCI Artwork
              run: cowsay -f dragon "Run for Cover" >> dragon.txt
