name: My First Workflow
on: push
jobs:
    first_job:
          strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
              os: [ ubuntu-latest, ubuntu-20.04, windows-latest ]
              images: [ hello-world, alpine ]
              exclude:
                - images: alpine
                  os: windows-latest
              include:
                - images: apd64/alpine
                  os: ubuntu-latest
          runs-on: ${{ matrix.images }}
          steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: List and read files
              run: |
                   echo "My first Github Actions Job"
                   ls -ltra
                   cat README.md
                   sudo apt-get install cowsay -y
            - name: Geneerate ASCI Artwork
              run: cowsay -f dragon "Run for Cover ${{ matrix.images }}" >> dragon.txt
