name: PARENT_WORKFLOW
on: 
  workflow_dispatch:  
jobs:
    first_job:
          runs-on: ubuntu-latest
          steps:
            - name: List and read files
              run: |
                   echo "My first Github Actions Job"