name: My First Workflow
on: push
jobs:
    first_job:
          runs-on: ubuntu-latest
          steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: List and read files
              run: |
                   echo "My first Github Actions Job"
                   ls -ltra
                   cat README.md
                   sudo apt-get install cowsay -y

            - name: Geneerate ASCI Artwork
              run: cowsay -f dragon "Run for Cover" >> dragon.txt

            - name: Print file
              run: cat dragon.txt